---
# Setup Nextcloud (Docker Compose)

- name: Setup server
  become: true
  hosts: all
  vars:
    docker_install_python_module: true
  roles:
    - docker
  tasks:
    - name: Run docker container with portainer server
      community.docker.docker_container:
        name: portainer-ce
        image: portainer/portainer-ce:2.18.1
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /opt/portainer:/data
        ports:
          - 9443:9443
  tags:
    - server

- name: Setup agents
  become: true
  hosts: all
  vars:
    docker_install_python_module: true
  roles:
    - docker
  tasks:
    - name: Run docker container with portainer client
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:2.18.1
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
          - 9001:9001

    - name: Allow portainer port in firewalld
      ansible.posix.firewalld:
        port: 9001/tcp
        permanent: true
        immediate: true
        state: enabled
  tags:
    - agent
